#!/bin/bash

set +e
set +v

# This script receives from STDIN the new KSK for the rollover in the following form : 
# <zone> <ttl> <class> <type> DNSKEY <flags> <protocol> <algorithm> <public key>

IN=`cat |sed -re 's/\t+/ /g;s/ +/ /g'`

COOKIE=`mktemp`
NIC="DLV_USERNAME"
PASS="THESUPERSECRETPASSWORD"
DLVZONECONF="/Path/To/Zone/Cookie/To/Include/in/Zone/Conf"
ODSSIGNER=ods-signer

source .config


if [[ -n "$CONF" ]]; then
    EXTRA_ARGS="--config $CONF"
fi;


DOMAIN=`echo -n $IN |cut -d ' ' -f 1|sed -re 's/\.$//'`

# Get Authentification token
PAGETOKEN=`curl -k -c $COOKIE --compressed -i  "https://dlv.isc.org/" -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Host: dlv.isc.org' 2>/dev/null |tr -d '\n'`

AUTH_N=`echo $PAGETOKEN |sed -re 's/.*window._auth_token_name *= *"([^"]+)".*/\1/'`
AUTH_V=`echo $PAGETOKEN |sed -re 's/.*window._auth_token *= *"([^"]+)".*/\1/'`

#Encode Auth token for form data

AUTH_N=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$AUTH_N")
AUTH_V=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$AUTH_V")

# LOGIN
curl -k -b $COOKIE -c $COOKIE --compressed -i 'https://dlv.isc.org/session' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Host: dlv.isc.org' -H 'Content-Type: application/x-www-form-urlencoded' --data "${AUTH_N}=${AUTH_V}&session%5Blogin%5D=${NIC}&session%5Bpassword%5D=${PASS}&commit=Log+In" 2>/dev/null >/dev/null


# GET UID
PAGEHOME=`curl -k -b $COOKIE -c $COOKIE --compressed -i 'https://dlv.isc.org/' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Host: dlv.isc.org' 2>/dev/null |tr -d '\n'`


DLVUID=`echo $PAGEHOME |sed -re 's|.*/users/([0-9]+)/zones.*|\1|'`

# GET ZONE ID

PAGEZONES=`curl -k -b $COOKIE -c $COOKIE --compressed -i "https://dlv.isc.org/users/$DLVUID/zones" -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Host: dlv.isc.org' 2>/dev/null |tr -d '\n'`

DLVZID=`echo $PAGEZONES|sed -e 's/<td>/\n/g'|grep $DOMAIN -A 1|grep "/dnskeys/new"|sed -re 's|.*"/zones/([0-9]+)/dnskeys/new".*|\1|'`


# # ADD KEY

#   # Encode Key

EIN=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$IN")

## "The format of the DNSKEY record you provided is not correct." < bad but don't care => DNSKEY already in

curl --compressed "https://dlv.isc.org/zones/${DLVZID}/dnskeys" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -b $COOKIE -H 'Content-Type: application/x-www-form-urlencoded' --data "${AUTH_N}=${AUTH_V}&dnskey%5Brecord%5D=$EIN&commit=Add+DNSKEY" 2>/dev/null >/dev/null


## Check Key and delete missing one

DLVKEYS=`curl --compressed "https://dlv.isc.org/zones/${DLVZID}" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -b $COOKIE 2>/dev/null|tr -d '\n' |sed -re 's|</?tr>|\n|g' |grep '"/dnskeys/' |sed -re 's|.*"/dnskeys/([0-9]+)".*|\1|g'`

ODSKEY=`ods-ksmutil $EXTRA_ARGS key list --verbose --zone $DOMAIN 2>/dev/null|grep "KSK" |grep -E "^$DOMAIN"|grep -Evi "DEAD|RETIRE"|sed -re 's/.* +([0-9]+)$/\1/g'|tr '\n' '|'`

for K in $DLVKEYS; do 
    TAGID=`curl --compressed "https://dlv.isc.org/dnskeys/$K" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -b $COOKIE 2>/dev/null|tr -d '\n' |sed -re 's|</?tr>|\n|g' |grep 'DNSKEY Tag' |sed -re 's|.*<td> *([^ <]+) *</td>.*|\1|g'`
    if echo "${ODSKEY}" |grep -qi "$TAGID|"; then
	echo "Key needed" 2>/dev/null >/dev/null
    else
	curl --compressed -b $COOKIE "https://dlv.isc.org/dnskeys/$K" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' --data "_method=delete&${AUTH_N}=${AUTH_V}" 2>/dev/null >/dev/null
    fi;
done


## Get DLV cookies for unchecked

DLVKEYS=`curl --compressed "https://dlv.isc.org/zones/${DLVZID}" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -b $COOKIE 2>/dev/null|tr -d '\n' |sed -re 's|</?tr>|\n|g' |grep '"/dnskeys/' |grep -e '<td> *No *</td>'|sed -re 's|.*"/dnskeys/([0-9]+)".*|\1|g'`

DLVCOOKIE=";; Automatic generation of DLV COOKIES\n"

for K in $DLVKEYS; do 
    C=`curl --compressed "https://dlv.isc.org/dnskeys/$K" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -b $COOKIE 2>/dev/null|tr -d '\n' |sed -re 's|</?tr>|\n|g' |grep 'TXT record value' |sed -re 's|.*<td> *(DLV[^ <]+) *</td>.*|\1|g'`
    DLVCOOKIE="$DLVCOOKIE\n dlv.$DOMAIN. 0 IN TXT \"$C\""
done;


# Use "$INCLUDE /Path/To/Stored/Cookie/dlv...." in zone file

echo -e "$DLVCOOKIE\n" > "${DLVZONECONF}/dlv.$DOMAIN.dns"

# resign domain with DLV cookie

$($ODSSIGER sign $DOMAIN 2>/dev/null >/dev/null)

# Sould be updated in minutes

# Request recheck
for K in $DLVKEYS; do 
    curl -b $COOKIE "https://dlv.isc.org/dnskeys/$K/recheck" -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' --data "_method=put&${AUTH_N}=${AUTH_V}" 2>/dev/null >/dev/null
done;

#LOGOUT
curl -b $COOKIE 'https://dlv.isc.org/session' -H 'Host: dlv.isc.org' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'  -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' --data "_method=delete&${AUTH_N}=${AUTH_V}" 2>/dev/null >/dev/null

rm -f $COOKIE
